<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "_teacher".
 *
 * @property integer $id
 * @property string $full_name
 * @property integer $age
 * @property string $phone
 * @property string $address
 * @property integer $gender
 * @property string $photo
 * @property integer $status
 * @property integer $is_deleted
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property \common\models\RelTeacherSubject[] $relTeacherSubjects
 * @property string $aliasModel
 */
abstract class Teacher extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '_teacher';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['full_name', 'gender'], 'required'],
            [['age', 'gender', 'status', 'is_deleted'], 'integer'],
            [['full_name', 'phone', 'address', 'photo'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'full_name' => Yii::t('models', 'Full Name'),
            'age' => Yii::t('models', 'Age'),
            'phone' => Yii::t('models', 'Phone'),
            'address' => Yii::t('models', 'Address'),
            'gender' => Yii::t('models', 'Gender'),
            'photo' => Yii::t('models', 'Photo'),
            'status' => Yii::t('models', 'Status'),
            'is_deleted' => Yii::t('models', 'Is Deleted'),
            'created_at' => Yii::t('models', 'Created At'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRelTeacherSubjects()
    {
        return $this->hasMany(\common\models\RelTeacherSubject::className(), ['teacher_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\TeacherQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\TeacherQuery(get_called_class());
    }


}
